import React, { useState } from 'react';
import { CheckCircle2, ChevronDown, Copy, Download, Share2 } from 'lucide-react';
import { authenticatedFetch } from '../utils/supabaseAuth';
import { SchoolTemplate } from '../types/schoolTemplate';

interface Props { content: string; subject: string; grade: string; className: string; bimester: number; template: SchoolTemplate | null; notify: (message: string) => void; }
const slug = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/gi, '_').replace(/^_|_$/g, '');
const copyFallback = (text: string) => { const input = document.createElement('textarea'); input.value = text; input.style.position = 'fixed'; input.style.opacity = '0'; document.body.appendChild(input); input.select(); document.execCommand('copy'); input.remove(); };

export const AssessmentReadyActions: React.FC<Props> = ({ content, subject, grade, className, bimester, template, notify }) => {
  const [menu, setMenu] = useState(false); const [busy, setBusy] = useState(false); const [shareUrl, setShareUrl] = useState('');
  const payload = { templateId: template?.id, title: 'Avaliação Bimestral', subject, grade, className, bimester, content, filename: slug(`Avaliacao_Bimestral_${subject}_${grade}`) };
  const getFile = async (format: 'docx' | 'pdf') => { const response = await authenticatedFetch(`/api/assessments/export/${format}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.error || 'Falha ao preparar arquivo.'); } return new File([await response.blob()], `${payload.filename}.${format}`, { type: format === 'pdf' ? 'application/pdf' : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' }); };
  const download = async (format: 'docx' | 'pdf') => { setBusy(true); setMenu(false); try { const file = await getFile(format); const url = URL.createObjectURL(file); const anchor = document.createElement('a'); anchor.href = url; anchor.download = file.name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); notify(`${format.toUpperCase()} baixado.`); } catch (error: any) { notify(error.message); } finally { setBusy(false); } };
  const ensureLink = async () => { if (shareUrl) return shareUrl; const response = await authenticatedFetch('/api/assessments/share', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Falha ao criar link.'); setShareUrl(data.url); return data.url as string; };
  const share = async () => { setBusy(true); try { const file = await getFile('pdf'); if (navigator.share && navigator.canShare?.({ files: [file] })) { await navigator.share({ title: `Avaliação — ${subject}`, text: 'Avaliação gerada no Aula Clara', files: [file] }); return; } const url = await ensureLink(); if (navigator.share) await navigator.share({ title: `Avaliação — ${subject}`, text: `Avaliação gerada no Aula Clara:\n${subject}\n\nAcesse:\n${url}`, url }); else window.open(`https://wa.me/?text=${encodeURIComponent(`Avaliação gerada no Aula Clara:\n${subject}\n\nAcesse:\n${url}`)}`, '_blank', 'noopener,noreferrer'); } catch (error: any) { if (error?.name !== 'AbortError') notify(error.message || 'Não foi possível compartilhar.'); } finally { setBusy(false); } };
  const copy = async () => { setBusy(true); try { const url = await ensureLink(); if (navigator.clipboard?.writeText) await navigator.clipboard.writeText(url); else copyFallback(url); notify('Link copiado.'); } catch (error: any) { notify(error.message || 'Não foi possível copiar o link.'); } finally { setBusy(false); } };
  return <div className="assessment-ready"><div><CheckCircle2 size={22}/><div><strong>Avaliação pronta</strong><small>Modelo: {template ? `${template.name} — ${template.schoolName}` : 'Padrão Aula Clara'}</small></div></div><div className="assessment-ready-buttons"><div className="assessment-download"><button type="button" disabled={busy} onClick={() => setMenu(!menu)}><Download size={18}/> Baixar <ChevronDown size={16}/></button>{menu && <div><button onClick={() => void download('docx')}>Baixar DOCX editável</button><button onClick={() => void download('pdf')}>Baixar PDF</button></div>}</div><button type="button" disabled={busy} onClick={() => void share()}><Share2 size={18}/> Compartilhar</button><button type="button" disabled={busy} onClick={() => void copy()}><Copy size={18}/> Copiar link</button></div></div>;
};
