import React, { useEffect, useRef, useState } from 'react';
import { Copy, Eye, FileUp, Pencil, Star, Trash2 } from 'lucide-react';
import { SchoolTemplate } from '../types/schoolTemplate';
import { authenticatedFetch } from '../utils/supabaseAuth';

interface Props { value: SchoolTemplate | null; onChange: (template: SchoolTemplate | null) => void; notify: (message: string) => void; }
interface Row { id: string; name: string; is_default: boolean; template_json: Omit<SchoolTemplate, 'id' | 'createdAt' | 'isDefault'>; created_at: string; }

const fileToDataUrl = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || '')); reader.onerror = reject; reader.readAsDataURL(file); });
const fromRow = (row: Row): SchoolTemplate => ({ ...row.template_json, id: row.id, name: row.name, isDefault: row.is_default, createdAt: row.created_at });

export const SchoolTemplateManager: React.FC<Props> = ({ value, onChange, notify }) => {
  const inputRef = useRef<HTMLInputElement>(null); const [rows, setRows] = useState<Row[]>([]); const [busy, setBusy] = useState(false);
  const [draft, setDraft] = useState<any>(null); const [name, setName] = useState('Avaliação Bimestral'); const [preview, setPreview] = useState<SchoolTemplate | null>(null);
  const load = async () => { try { const response = await authenticatedFetch('/api/school-templates'); const data = await response.json(); if (!response.ok) throw new Error(data.error); const next = data.templates || []; setRows(next); const selected = next.find((row: Row) => row.id === value?.id) || next.find((row: Row) => row.is_default); if (!value && selected) onChange(fromRow(selected)); } catch (error: any) { notify(error.message || 'Não foi possível carregar os modelos.'); } };
  useEffect(() => { void load(); }, []);

  const analyze = async (file: File) => { setBusy(true); try { const base64 = await fileToDataUrl(file); const response = await authenticatedFetch('/api/school-templates/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ file: { name: file.name, mimeType: file.type, base64 } }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setDraft(data.template); setName(data.template.name || file.name.replace(/\.(docx|pdf)$/i, '')); } catch (error: any) { notify(error.message || 'Falha ao analisar o modelo.'); } finally { setBusy(false); if (inputRef.current) inputRef.current.value = ''; } };
  const save = async (isDefault: boolean) => { if (!draft || !name.trim()) return; setBusy(true); try { const response = await authenticatedFetch('/api/school-templates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: name.trim(), isDefault, template: { ...draft, name: name.trim() } }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); const selected = fromRow(data.template); onChange(selected); setDraft(null); await load(); notify(isDefault ? 'Modelo salvo e definido como padrão.' : 'Modelo salvo com segurança.'); } catch (error: any) { notify(error.message || 'Falha ao salvar modelo.'); } finally { setBusy(false); } };
  const update = async (row: Row, operation: 'default' | 'rename' | 'duplicate' | 'delete') => {
    try {
      if (operation === 'delete') { if (!confirm(`Excluir o modelo “${row.name}”?`)) return; const response = await authenticatedFetch(`/api/school-templates/${row.id}`, { method: 'DELETE' }); if (!response.ok) throw new Error('Não foi possível excluir.'); if (value?.id === row.id) onChange(null); }
      else if (operation === 'default') { const response = await authenticatedFetch(`/api/school-templates/${row.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ isDefault: true }) }); if (!response.ok) throw new Error('Não foi possível definir o padrão.'); onChange({ ...fromRow(row), isDefault: true }); }
      else if (operation === 'rename') { const next = prompt('Novo nome do modelo:', row.name)?.trim(); if (!next) return; const response = await authenticatedFetch(`/api/school-templates/${row.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: next }) }); if (!response.ok) throw new Error('Não foi possível renomear.'); }
      else { const response = await authenticatedFetch('/api/school-templates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: `${row.name} — cópia`, template: row.template_json }) }); if (!response.ok) throw new Error('Não foi possível duplicar.'); }
      await load(); notify('Modelos atualizados.');
    } catch (error: any) { notify(error.message || 'Falha ao atualizar modelo.'); }
  };

  return <section className="school-template-card">
    <div className="school-template-heading"><div><span>MODELO DA ESCOLA</span><h3>Use o padrão visual do seu colégio</h3><p>Envie DOCX ou PDF. Questões, respostas, gabaritos e dados pessoais do arquivo antigo são descartados.</p></div></div>
    <input ref={inputRef} hidden type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/pdf" onChange={(event) => { const file = event.target.files?.[0]; if (file) void analyze(file); }}/>
    <button type="button" className="school-template-upload" disabled={busy} onClick={() => inputRef.current?.click()}><FileUp size={18}/>{busy ? ' Analisando estrutura…' : ' Enviar modelo DOCX ou PDF'}</button>
    {draft && <div className="school-template-preview"><div><b>{draft.schoolName}</b><small>{draft.headerLines?.join(' · ')}</small><label>Como deseja chamar este modelo?<input value={name} onChange={(e) => setName(e.target.value)} /></label><label><input type="checkbox" checked={draft.keepInstructions} onChange={(e) => setDraft({ ...draft, keepInstructions: e.target.checked })}/> Manter orientações como padrão</label></div><button type="button" onClick={() => void save(false)}>Salvar como modelo</button><button type="button" onClick={() => void save(true)}>Salvar e definir padrão</button></div>}
    <div className="school-template-list"><strong>MEUS MODELOS</strong><button type="button" className={!value ? 'selected' : ''} onClick={() => onChange(null)}>Padrão Aula Clara</button>{rows.map((row) => <div key={row.id} className={`school-template-row ${value?.id === row.id ? 'selected' : ''}`}><button type="button" onClick={() => onChange(fromRow(row))}>{row.is_default ? '⭐ ' : ''}{row.name}<small>{row.template_json.schoolName}</small></button><div><button title="Visualizar" onClick={() => setPreview(fromRow(row))}><Eye size={16}/></button><button title="Renomear" onClick={() => void update(row, 'rename')}><Pencil size={16}/></button><button title="Duplicar" onClick={() => void update(row, 'duplicate')}><Copy size={16}/></button><button title="Definir como padrão" onClick={() => void update(row, 'default')}><Star size={16}/></button><button title="Excluir" onClick={() => void update(row, 'delete')}><Trash2 size={16}/></button></div></div>)}</div>
    {preview && <div className="school-template-a4" onClick={() => setPreview(null)}><article onClick={(e) => e.stopPropagation()}>{preview.logoDataUrl && <img src={preview.logoDataUrl} alt="Logo da escola"/>}<h2>{preview.schoolName}</h2>{preview.headerLines.map((line) => <p key={line}>{line}</p>)}<h3>AVALIAÇÃO DE {'{{DISCIPLINA}}'} — {'{{BIMESTRE}}'}</h3><p>ALUNO(A): __________________ Nº ____ TURMA: ______ NOTA: ____ DATA: ___/___/___</p>{preview.instructions?.map((line) => <small key={line}>• {line}</small>)}<button onClick={() => setPreview(null)}>Fechar preview</button></article></div>}
  </section>;
};
