alter table public.access_grants add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.access_grants add column if not exists deleted_at timestamptz;
alter table public.access_grants add column if not exists signup_source text not null default 'google';
alter table public.access_grants add column if not exists plan text not null default 'trial_15_days';
alter table public.access_grants drop constraint if exists access_grants_status_check;
alter table public.access_grants add constraint access_grants_status_check check (status in ('active','blocked','deleted'));
update public.access_grants g set user_id=u.id from auth.users u where lower(g.email)=lower(u.email) and g.user_id is null;
create unique index if not exists access_grants_user_id_key on public.access_grants(user_id) where user_id is not null;

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  event_type text not null check (event_type in ('registration','registration_error','expiration')),
  target_email text,
  title text not null,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);
alter table public.admin_notifications enable row level security;
grant select, update on public.admin_notifications to authenticated;
grant all on public.admin_notifications to service_role;
drop policy if exists master_read_admin_notifications on public.admin_notifications;
create policy master_read_admin_notifications on public.admin_notifications for select to authenticated using (public.is_aula_clara_master());
drop policy if exists master_update_admin_notifications on public.admin_notifications;
create policy master_update_admin_notifications on public.admin_notifications for update to authenticated using (public.is_aula_clara_master()) with check (public.is_aula_clara_master());

create or replace function public.handle_aula_clara_signup()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  v_email text := lower(new.email);
  v_name text := nullif(coalesce(new.raw_user_meta_data ->> 'name', new.raw_user_meta_data ->> 'full_name', ''), '');
  v_source text := coalesce(new.raw_app_meta_data ->> 'provider', 'google');
begin
  if new.email is null then return new; end if;
  insert into public.access_grants (user_id,email,display_name,role,status,lifetime,expires_at,created_at,updated_at,admin_reviewed_at,signup_source,plan,deleted_at)
  values (new.id,v_email,v_name,case when v_email='ecomnixx@gmail.com' then 'master' else 'client' end,'active',v_email='ecomnixx@gmail.com',case when v_email='ecomnixx@gmail.com' then null else now()+interval '15 days' end,now(),now(),case when v_email='ecomnixx@gmail.com' then now() else null end,v_source,case when v_email='ecomnixx@gmail.com' then 'lifetime' else 'trial_15_days' end,null)
  on conflict (email) do update set user_id=excluded.user_id,display_name=coalesce(public.access_grants.display_name,excluded.display_name),updated_at=now(),signup_source=excluded.signup_source;
  insert into public.access_events(access_email,action,days_delta,performed_by,created_at) values(v_email,'registration',15,'system',now());
  if v_email <> 'ecomnixx@gmail.com' then
    insert into public.admin_notifications(event_key,event_type,target_email,title,body,created_at)
    values('registration:'||new.id::text,'registration',v_email,'Novo professor cadastrado',coalesce(v_name,v_email)||' ('||v_email||')',now())
    on conflict(event_key) do nothing;
  end if;
  return new;
end;
$$;
revoke all on function public.handle_aula_clara_signup() from public, anon, authenticated;
